sudo: false
language: cpp
os:
  - linux
env:
  global:
    # "borrow" from nodemcu guys
    - ESP_OPEN_SDK_BIN: https://github.com/nodemcu/nodemcu-firmware/raw/2d958750b56fc60297f564b4ec303e47928b5927/tools/esp-open-sdk.tar.xz
    - DEPLOY_DIR: $TRAVIS_BUILD_DIR/deploy
    - ARTIFACTS_DIR: $TRAVIS_BUILD_DIR/out/firmware

addons:
  apt:
    packages: make unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk ncurses-dev libexpat-dev python-dev python python-serial sed git unzip bash help2man wget bzip2
    
install:
  - export SDK_FILE_NAME="esp-alt-sdk-v${SDK_VERSION}.${SDK_BUILD}-linux-x86_64.tar.gz"
  - mkdir -p $TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk
  - wget https://bintray.com/artifact/download/kireevco/generic/${SDK_FILE_NAME}
  - bsdtar -xf ${SDK_FILE_NAME} -C $TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk  
  - rm -rf samples
  - export SMING_HOME=$TRAVIS_BUILD_DIR/Sming/Sming
    
script:
  - export ESP_HOME=$TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk  
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk/utils/
  - cd $TRAVIS_BUILD_DIR
  - SMING_RELEASE=1 make all
  
after_success: 
  - bash deploy_release_ghpages.sh

